name = "mellowcode-company-website"
type = "javascript"
main = "public/index.js"

# Cloudflare Pages configuration
pages_build_output_dir = "out"

[env.production]
name = "mellowcode-company-website"
